--TEST--
Dottie::Result works as expected
--FILE--
require "../../lib/dottie"
require "../../lib/dottie/result/expected_failure"
require "../../lib/dottie/result/failure"
require "../../lib/dottie/result/skipped"
require "../../lib/dottie/result/success"

def print_result(result)
  puts <<~TEXT
    test_name: #{result.test_name}
    success? #{result.success?}
    skipped? #{result.skipped?}
    expected_failure? #{result.expected_failure?}
    failure? #{result.failure?}
  TEXT
end

puts "Can be a failure"
failure = Dottie::Result::Failure.new("-", 1234, 5679)
print_result(failure)
puts "expected_output: #{failure.expected_output}"
puts "actual_output: #{failure.actual_output}"

puts "\nCan be successful"
print_result(Dottie::Result::Success.new("-"))

puts "\nCan be skipped"
print_result(Dottie::Result::Skipped.new("-"))

puts "\nCan be an expected failure"
print_result(Dottie::Result::ExpectedFailure.new("-"))
--EXPECT--
Can be a failure
test_name: -
success? false
skipped? false
expected_failure? false
failure? true
expected_output: 1234
actual_output: 5679

Can be successful
test_name: -
success? true
skipped? false
expected_failure? false
failure? false

Can be skipped
test_name: -
success? false
skipped? true
expected_failure? false
failure? false

Can be an expected failure
test_name: -
success? false
skipped? false
expected_failure? true
failure? false
